apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, 
  #and be in the form: <plural>.<group>
  name: sharedsecrets.veccsolutions.com
spec:
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: sharedsecrets
    # singular name to be used as an alias on the CLI and for display
    singular: sharedsecret
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: SharedSecret
  # group name to use for REST API: /apis/<group>/<version>
  group: veccsolutions.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              allOf:
              - required:
                - source
                - target
              properties:
                source:
                  type: object
                  allOf:
                  - required:
                    - namespace
                    - name
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                target:
                  type: object
                  allOf:
                  - required:
                    - allowedNamespaces
                  properties:
                    allowedNamespaces:
                      type: array
                      items:
                        type: string
                    disalowedNamespaces:
                      type: array
                      items:
                        type: string
